Porfolio/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace PorfolioWeb.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Porfolio/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace PorfolioWeb.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Porfolio/Controllers/ExperienceController.cs
using Microsoft.AspNetCore.Mvc;

namespace PorfolioWeb.Controllers
{
    public class ExperienceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Porfolio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using PorfolioWeb.Dto;
using System.Diagnostics;

namespace PorfolioWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly Serilog.ILogger _logger;
        private readonly IStringLocalizer<HomeController> _localizer;

        public HomeController(Serilog.ILogger logger, IStringLocalizer<HomeController> localizer)
        {

            _logger = logger;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            try
            {
                var experiences = new List<ExperienceDto>
                {
                    new ExperienceDto {
                        Title = _localizer["FullStackDeveloper"],
                        Company = "Heinleing Grouppe",
                        Period = "Jan 2024 - Present",
                        Responsibilities = new List<ResponsibilitiesDto>() {
                            new ResponsibilitiesDto
                            {
                                Description = _localizer["DevelopingWebApplications"],
                                Category = "Category"
                            },
                        },

                        Technologies = new List<TechnologiesDto>()
                        {
                            new TechnologiesDto
                            {
                                Category = "Category",
                                Framework = new List<string> {".NET 8", "Bootstrap", "SQL Server" }
                            },
                        }
                    },
                };
                return View(experiences);
            }
            catch (Exception ex)
            {
                _logger.Error(ex, "Error en {accion} de {controller}", ControllerContext.RouteData.Values["action"]?.ToString(), ControllerContext.RouteData.Values["controller"]?.ToString());
                return Error();
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorDto { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Porfolio/Controllers/SkillsController.cs
using Microsoft.AspNetCore.Mvc;

namespace PorfolioWeb.Controllers
{
    public class SkillsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Porfolio/Views/About/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using PorfolioWeb.Dto

@inject IViewLocalizer Localizer
@model AboutDto

<h1>@Localizer["Welcome"]</h1>

Porfolio/Views/Contact/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using PorfolioWeb.Dto
@inject IViewLocalizer Localizer
@model MailRequestDto

@{
}

Porfolio/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Porfolio/Views/Home/_TechnologiesPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Porfolio/Views/Shared/_Footer.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
}

<div class="social-links">
    <a href="https://wa.me/5491141476732" target="_blank" class="whatsapp">
        <i class="fab fa-whatsapp"></i> WhatsApp
    </a>
    <a href="https://www.linkedin.com/in/jonathangdurante" target="_blank" class="linkedin">
        <i class="fab fa-linkedin"></i> LinkedIn
    </a>
    <a href="https://github.com/JonaDurante" target="_blank" class="github">
        <i class="fab fa-github"></i> GitHub
    </a>
</div>

Porfolio/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Porfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Porfolio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Porfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">@Localizer["About"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">@Localizer["About"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skills" asp-action="Index">@Localizer["Skills"]</a>
                        </li>
                        <li class="nav-item">
                            <a href="/docs/CV-Jonathan-Durante-EN.pdf" download class="btn btn-primary">
                                <i class="fas fa-download"></i> Download CV (English)
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/docs/CV-Jonathan-Durante-ES.pdf" download class="btn btn-primary">
                                <i class="fas fa-download"></i> Descargar CV (Español)
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Porfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Porfolio/Views/Shared/_Navigation.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

Porfolio/Views/Skills/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}